#############################################################################
# Makefile for building: gui_opengl.js
# Generated by qmake (3.1) (Qt 5.12.0)
# Project:  gui_opengl.pro
# Template: app
# Command: /Users/ynumajir/Qt/build/qtbase/bin/qmake -o Makefile gui_opengl.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = emcc
CXX           = em++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -s USE_LIBPNG=1 -s USE_FREETYPE=1 -s USE_ZLIB=1 -O3 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -s USE_LIBPNG=1 -s USE_FREETYPE=1 -s USE_ZLIB=1 -O3 -std=gnu++11 -Wall -W $(DEFINES)
INCPATH       = -I. -I../../../Qt/5.12.0/Src/qtbase/include -I../../../Qt/build/qtbase/include -I../../../Qt/5.12.0/Src/qtbase/include/QtGui -I../../../Qt/build/qtbase/include/QtGui -I../../../Qt/5.12.0/Src/qtbase/include/QtCore -I../../../Qt/build/qtbase/include/QtCore -I.moc -I/Users/ynumajir/.emscripten_ports/openssl/include -I../../../Qt/5.12.0/Src/qtbase/mkspecs/wasm-emscripten
QMAKE         = /Users/ynumajir/Qt/build/qtbase/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /Users/ynumajir/Qt/build/qtbase/bin/qmake -install qinstall
QINSTALL_PROGRAM = /Users/ynumajir/Qt/build/qtbase/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = gui_opengl.js1.0.0
DISTDIR = /Users/ynumajir/Downloads/qt-webassembly-examples-master/gui_opengl/.obj/gui_opengl.js1.0.0
LINK          = em++
LFLAGS        = -s WASM=1 -s FULL_ES2=1 -s ALLOW_MEMORY_GROWTH=1 -s USE_WEBGL2=1 -s NO_EXIT_RUNTIME=0 -s ERROR_ON_UNDEFINED_SYMBOLS=1 --bind -s "BINARYEN_METHOD='native-wasm'" -s "BINARYEN_TRAP_MODE='clamp'" -O3 -L/Users/ynumajir/Qt/build/qtbase/lib -lqtfreetype -s USE_LIBPNG=1
LIBS          = $(SUBLIBS) -L/Users/ynumajir/Qt/build/qtbase/plugins/platforms -L/Users/ynumajir/Qt/build/qtbase/lib -s USE_ZLIB=1 -s USE_LIBPNG=1 -s -s -s -s -s -s -s -s -s -s -s -s -s -s -s -s -s -s -s -s -s -s -s -s -s -s -s -s -s -s -s -s -s -s -s -s -s -s -s -s -s -s -s -s -s -s -s -s -s -s -s -s -s -s -lwasm -lQt5EventDispatcherSupport -s -s -s -s -lQt5FontDatabaseSupport -s -s -s -s -lqtfreetype -s -s -lQt5EglSupport -s -s -s -s -s -s -s -s -L/Users/ynumajir/Qt/build/qtbase/plugins/imageformats -lqgif -s -s -s -s -lqico -s -s -s -s -lqjpeg -s -s -s -s -lQt5Gui -s -s -lqtharfbuzz -s -lQt5Core -s -lqtpcre2   
AR            = emar cqs
RANLIB        = 
SED           = sed
STRIP         = 

####### Output directory

OBJECTS_DIR   = .obj/

####### Files

SOURCES       = hellowindow.cpp \
		main.cpp /Users/ynumajir/Downloads/qt-webassembly-examples-master/gui_opengl/gui_opengl.js_plugin_import.cpp
OBJECTS       = .obj/hellowindow.o \
		.obj/main.o \
		.obj/gui_opengl.js_plugin_import.o
DIST          = ../../../Qt/5.12.0/Src/qtbase/mkspecs/features/spec_pre.prf \
		../../../Qt/5.12.0/Src/qtbase/mkspecs/common/sanitize.conf \
		../../../Qt/5.12.0/Src/qtbase/mkspecs/common/gcc-base.conf \
		../../../Qt/5.12.0/Src/qtbase/mkspecs/common/clang.conf \
		../../../Qt/build/qtbase/mkspecs/qconfig.pri \
		../../../Qt/build/qtbase/mkspecs/modules/qt_ext_freetype.pri \
		../../../Qt/build/qtbase/mkspecs/modules/qt_ext_harfbuzz.pri \
		../../../Qt/build/qtbase/mkspecs/modules/qt_ext_pcre2.pri \
		../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_accessibility_support_private.pri \
		../../../Qt/build/qtbase/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_bootstrap_private.pri \
		../../../Qt/build/qtbase/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_core.pri \
		../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_core_private.pri \
		../../../Qt/build/qtbase/mkspecs/modules/qt_lib_core.pri \
		../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_devicediscovery_support_private.pri \
		../../../Qt/build/qtbase/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_edid_support_private.pri \
		../../../Qt/build/qtbase/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_egl_support_private.pri \
		../../../Qt/build/qtbase/mkspecs/modules/qt_lib_egl_support_private.pri \
		../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_eventdispatcher_support_private.pri \
		../../../Qt/build/qtbase/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_fb_support_private.pri \
		../../../Qt/build/qtbase/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_fontdatabase_support_private.pri \
		../../../Qt/build/qtbase/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_gui.pri \
		../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_gui_private.pri \
		../../../Qt/build/qtbase/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_network.pri \
		../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_network_private.pri \
		../../../Qt/build/qtbase/mkspecs/modules/qt_lib_network.pri \
		../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_opengl.pri \
		../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_opengl_private.pri \
		../../../Qt/build/qtbase/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_openglextensions.pri \
		../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_openglextensions_private.pri \
		../../../Qt/build/qtbase/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_platformcompositor_support_private.pri \
		../../../Qt/build/qtbase/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_printsupport.pri \
		../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_printsupport_private.pri \
		../../../Qt/build/qtbase/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_qml.pri \
		../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_qml_private.pri \
		../../../Qt/build/qtbase/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_qmldevtools_private.pri \
		../../../Qt/build/qtbase/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_qmltest.pri \
		../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_qmltest_private.pri \
		../../../Qt/build/qtbase/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_quick.pri \
		../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_quick_private.pri \
		../../../Qt/build/qtbase/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_quickparticles_private.pri \
		../../../Qt/build/qtbase/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_quickshapes_private.pri \
		../../../Qt/build/qtbase/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_quickwidgets.pri \
		../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_quickwidgets_private.pri \
		../../../Qt/build/qtbase/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_service_support_private.pri \
		../../../Qt/build/qtbase/mkspecs/modules/qt_lib_service_support_private.pri \
		../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_svg.pri \
		../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_svg_private.pri \
		../../../Qt/build/qtbase/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_testlib.pri \
		../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_testlib_private.pri \
		../../../Qt/build/qtbase/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_theme_support_private.pri \
		../../../Qt/build/qtbase/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_widgets.pri \
		../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_widgets_private.pri \
		../../../Qt/build/qtbase/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_xml.pri \
		../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_xml_private.pri \
		../../../Qt/build/qtbase/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_zlib_private.pri \
		../../../Qt/build/qtbase/mkspecs/modules/qt_lib_zlib_private.pri \
		../../../Qt/build/qtbase/mkspecs/modules/qt_plugin_qgif.pri \
		../../../Qt/build/qtbase/mkspecs/modules/qt_plugin_qico.pri \
		../../../Qt/build/qtbase/mkspecs/modules/qt_plugin_qjpeg.pri \
		../../../Qt/build/qtbase/mkspecs/modules/qt_plugin_qsvg.pri \
		../../../Qt/build/qtbase/mkspecs/modules/qt_plugin_qsvgicon.pri \
		../../../Qt/build/qtbase/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri \
		../../../Qt/build/qtbase/mkspecs/modules/qt_plugin_wasm.pri \
		../../../Qt/build/qtbase/mkspecs/modules/qt_tool_syncqt.pri \
		../../../Qt/5.12.0/Src/qtbase/mkspecs/features/qt_functions.prf \
		../../../Qt/5.12.0/Src/qtbase/mkspecs/features/qt_config.prf \
		../../../Qt/5.12.0/Src/qtbase/mkspecs/wasm-emscripten/qmake.conf \
		../../../Qt/5.12.0/Src/qtbase/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../Qt/5.12.0/Src/qtbase/mkspecs/features/exclusive_builds.prf \
		../../../Qt/5.12.0/Src/qtbase/mkspecs/features/toolchain.prf \
		../../../Qt/5.12.0/Src/qtbase/mkspecs/features/default_pre.prf \
		../../../Qt/5.12.0/Src/qtbase/mkspecs/features/resolve_config.prf \
		../../../Qt/5.12.0/Src/qtbase/mkspecs/features/default_post.prf \
		../../../Qt/5.12.0/Src/qtbase/mkspecs/features/wasm/wasm.prf \
		../../../Qt/5.12.0/Src/qtbase/mkspecs/features/warn_on.prf \
		../../../Qt/build/qtbase/plugins/platforms/libwasm.prl \
		../../../Qt/5.12.0/Src/qtbase/mkspecs/features/qt.prf \
		../../../Qt/5.12.0/Src/qtbase/mkspecs/features/wasm/qt.prf \
		../../../Qt/5.12.0/Src/qtbase/mkspecs/features/resources.prf \
		../../../Qt/5.12.0/Src/qtbase/mkspecs/features/moc.prf \
		../../../Qt/5.12.0/Src/qtbase/mkspecs/features/unix/opengl.prf \
		../../../Qt/5.12.0/Src/qtbase/mkspecs/features/unix/thread.prf \
		../../../Qt/5.12.0/Src/qtbase/mkspecs/features/qmake_use.prf \
		../../../Qt/5.12.0/Src/qtbase/mkspecs/features/file_copies.prf \
		../../../Qt/5.12.0/Src/qtbase/mkspecs/features/testcase_targets.prf \
		../../../Qt/5.12.0/Src/qtbase/mkspecs/features/exceptions.prf \
		../../../Qt/5.12.0/Src/qtbase/mkspecs/features/yacc.prf \
		../../../Qt/5.12.0/Src/qtbase/mkspecs/features/lex.prf \
		gui_opengl.pro hellowindow.h hellowindow.cpp \
		main.cpp
QMAKE_TARGET  = gui_opengl.js
DESTDIR       = 
TARGET        = gui_opengl.js


first: all
####### Build rules

gui_opengl.js: /Users/ynumajir/Qt/build/qtbase/lib/libQt5Gui.a /Users/ynumajir/Qt/build/qtbase/lib/libQt5Core.a $(OBJECTS)  apphtml appjs appsvg
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: gui_opengl.pro ../../../Qt/5.12.0/Src/qtbase/mkspecs/wasm-emscripten/qmake.conf ../../../Qt/5.12.0/Src/qtbase/mkspecs/features/spec_pre.prf \
		../../../Qt/5.12.0/Src/qtbase/mkspecs/common/sanitize.conf \
		../../../Qt/5.12.0/Src/qtbase/mkspecs/common/gcc-base.conf \
		../../../Qt/5.12.0/Src/qtbase/mkspecs/common/clang.conf \
		../../../Qt/build/qtbase/mkspecs/qconfig.pri \
		../../../Qt/build/qtbase/mkspecs/modules/qt_ext_freetype.pri \
		../../../Qt/build/qtbase/mkspecs/modules/qt_ext_harfbuzz.pri \
		../../../Qt/build/qtbase/mkspecs/modules/qt_ext_pcre2.pri \
		../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_accessibility_support_private.pri \
		../../../Qt/build/qtbase/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_bootstrap_private.pri \
		../../../Qt/build/qtbase/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_core.pri \
		../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_core_private.pri \
		../../../Qt/build/qtbase/mkspecs/modules/qt_lib_core.pri \
		../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_devicediscovery_support_private.pri \
		../../../Qt/build/qtbase/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_edid_support_private.pri \
		../../../Qt/build/qtbase/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_egl_support_private.pri \
		../../../Qt/build/qtbase/mkspecs/modules/qt_lib_egl_support_private.pri \
		../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_eventdispatcher_support_private.pri \
		../../../Qt/build/qtbase/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_fb_support_private.pri \
		../../../Qt/build/qtbase/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_fontdatabase_support_private.pri \
		../../../Qt/build/qtbase/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_gui.pri \
		../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_gui_private.pri \
		../../../Qt/build/qtbase/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_network.pri \
		../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_network_private.pri \
		../../../Qt/build/qtbase/mkspecs/modules/qt_lib_network.pri \
		../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_opengl.pri \
		../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_opengl_private.pri \
		../../../Qt/build/qtbase/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_openglextensions.pri \
		../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_openglextensions_private.pri \
		../../../Qt/build/qtbase/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_platformcompositor_support_private.pri \
		../../../Qt/build/qtbase/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_printsupport.pri \
		../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_printsupport_private.pri \
		../../../Qt/build/qtbase/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_qml.pri \
		../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_qml_private.pri \
		../../../Qt/build/qtbase/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_qmldevtools_private.pri \
		../../../Qt/build/qtbase/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_qmltest.pri \
		../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_qmltest_private.pri \
		../../../Qt/build/qtbase/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_quick.pri \
		../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_quick_private.pri \
		../../../Qt/build/qtbase/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_quickparticles_private.pri \
		../../../Qt/build/qtbase/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_quickshapes_private.pri \
		../../../Qt/build/qtbase/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_quickwidgets.pri \
		../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_quickwidgets_private.pri \
		../../../Qt/build/qtbase/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_service_support_private.pri \
		../../../Qt/build/qtbase/mkspecs/modules/qt_lib_service_support_private.pri \
		../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_svg.pri \
		../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_svg_private.pri \
		../../../Qt/build/qtbase/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_testlib.pri \
		../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_testlib_private.pri \
		../../../Qt/build/qtbase/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_theme_support_private.pri \
		../../../Qt/build/qtbase/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_widgets.pri \
		../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_widgets_private.pri \
		../../../Qt/build/qtbase/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_xml.pri \
		../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_xml_private.pri \
		../../../Qt/build/qtbase/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_zlib_private.pri \
		../../../Qt/build/qtbase/mkspecs/modules/qt_lib_zlib_private.pri \
		../../../Qt/build/qtbase/mkspecs/modules/qt_plugin_qgif.pri \
		../../../Qt/build/qtbase/mkspecs/modules/qt_plugin_qico.pri \
		../../../Qt/build/qtbase/mkspecs/modules/qt_plugin_qjpeg.pri \
		../../../Qt/build/qtbase/mkspecs/modules/qt_plugin_qsvg.pri \
		../../../Qt/build/qtbase/mkspecs/modules/qt_plugin_qsvgicon.pri \
		../../../Qt/build/qtbase/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri \
		../../../Qt/build/qtbase/mkspecs/modules/qt_plugin_wasm.pri \
		../../../Qt/build/qtbase/mkspecs/modules/qt_tool_syncqt.pri \
		../../../Qt/5.12.0/Src/qtbase/mkspecs/features/qt_functions.prf \
		../../../Qt/5.12.0/Src/qtbase/mkspecs/features/qt_config.prf \
		../../../Qt/5.12.0/Src/qtbase/mkspecs/wasm-emscripten/qmake.conf \
		../../../Qt/5.12.0/Src/qtbase/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../Qt/5.12.0/Src/qtbase/mkspecs/features/exclusive_builds.prf \
		../../../Qt/5.12.0/Src/qtbase/mkspecs/features/toolchain.prf \
		../../../Qt/5.12.0/Src/qtbase/mkspecs/features/default_pre.prf \
		../../../Qt/5.12.0/Src/qtbase/mkspecs/features/resolve_config.prf \
		../../../Qt/5.12.0/Src/qtbase/mkspecs/features/default_post.prf \
		../../../Qt/5.12.0/Src/qtbase/mkspecs/features/wasm/wasm.prf \
		../../../Qt/5.12.0/Src/qtbase/mkspecs/features/warn_on.prf \
		../../../Qt/build/qtbase/plugins/platforms/libwasm.prl \
		../../../Qt/5.12.0/Src/qtbase/mkspecs/features/qt.prf \
		../../../Qt/5.12.0/Src/qtbase/mkspecs/features/wasm/qt.prf \
		../../../Qt/5.12.0/Src/qtbase/mkspecs/features/resources.prf \
		../../../Qt/5.12.0/Src/qtbase/mkspecs/features/moc.prf \
		../../../Qt/5.12.0/Src/qtbase/mkspecs/features/unix/opengl.prf \
		../../../Qt/5.12.0/Src/qtbase/mkspecs/features/unix/thread.prf \
		../../../Qt/5.12.0/Src/qtbase/mkspecs/features/qmake_use.prf \
		../../../Qt/5.12.0/Src/qtbase/mkspecs/features/file_copies.prf \
		../../../Qt/5.12.0/Src/qtbase/mkspecs/features/testcase_targets.prf \
		../../../Qt/5.12.0/Src/qtbase/mkspecs/features/exceptions.prf \
		../../../Qt/5.12.0/Src/qtbase/mkspecs/features/yacc.prf \
		../../../Qt/5.12.0/Src/qtbase/mkspecs/features/lex.prf \
		gui_opengl.pro \
		../../../Qt/build/qtbase/lib/libQt5EventDispatcherSupport.prl \
		../../../Qt/build/qtbase/lib/libQt5FontDatabaseSupport.prl \
		../../../Qt/build/qtbase/lib/libqtfreetype.prl \
		../../../Qt/build/qtbase/lib/libQt5EglSupport.prl \
		../../../Qt/build/qtbase/lib/libQt5Gui.prl \
		../../../Qt/build/qtbase/lib/libqtharfbuzz.prl \
		../../../Qt/build/qtbase/lib/libQt5Core.prl \
		../../../Qt/build/qtbase/lib/libqtpcre2.prl \
		../../../Qt/build/qtbase/plugins/imageformats/libqgif.prl \
		../../../Qt/build/qtbase/plugins/imageformats/libqico.prl \
		../../../Qt/build/qtbase/plugins/imageformats/libqjpeg.prl
	$(QMAKE) -o Makefile gui_opengl.pro
../../../Qt/5.12.0/Src/qtbase/mkspecs/features/spec_pre.prf:
../../../Qt/5.12.0/Src/qtbase/mkspecs/common/sanitize.conf:
../../../Qt/5.12.0/Src/qtbase/mkspecs/common/gcc-base.conf:
../../../Qt/5.12.0/Src/qtbase/mkspecs/common/clang.conf:
../../../Qt/build/qtbase/mkspecs/qconfig.pri:
../../../Qt/build/qtbase/mkspecs/modules/qt_ext_freetype.pri:
../../../Qt/build/qtbase/mkspecs/modules/qt_ext_harfbuzz.pri:
../../../Qt/build/qtbase/mkspecs/modules/qt_ext_pcre2.pri:
../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_accessibility_support_private.pri:
../../../Qt/build/qtbase/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_bootstrap_private.pri:
../../../Qt/build/qtbase/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_core.pri:
../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_core_private.pri:
../../../Qt/build/qtbase/mkspecs/modules/qt_lib_core.pri:
../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_devicediscovery_support_private.pri:
../../../Qt/build/qtbase/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_edid_support_private.pri:
../../../Qt/build/qtbase/mkspecs/modules/qt_lib_edid_support_private.pri:
../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_egl_support_private.pri:
../../../Qt/build/qtbase/mkspecs/modules/qt_lib_egl_support_private.pri:
../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_eventdispatcher_support_private.pri:
../../../Qt/build/qtbase/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_fb_support_private.pri:
../../../Qt/build/qtbase/mkspecs/modules/qt_lib_fb_support_private.pri:
../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_fontdatabase_support_private.pri:
../../../Qt/build/qtbase/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_gui.pri:
../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_gui_private.pri:
../../../Qt/build/qtbase/mkspecs/modules/qt_lib_gui.pri:
../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_network.pri:
../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_network_private.pri:
../../../Qt/build/qtbase/mkspecs/modules/qt_lib_network.pri:
../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_opengl.pri:
../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_opengl_private.pri:
../../../Qt/build/qtbase/mkspecs/modules/qt_lib_opengl.pri:
../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_openglextensions.pri:
../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_openglextensions_private.pri:
../../../Qt/build/qtbase/mkspecs/modules/qt_lib_openglextensions.pri:
../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_platformcompositor_support_private.pri:
../../../Qt/build/qtbase/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_printsupport.pri:
../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_printsupport_private.pri:
../../../Qt/build/qtbase/mkspecs/modules/qt_lib_printsupport.pri:
../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_qml.pri:
../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_qml_private.pri:
../../../Qt/build/qtbase/mkspecs/modules/qt_lib_qml.pri:
../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_qmldevtools_private.pri:
../../../Qt/build/qtbase/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_qmltest.pri:
../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_qmltest_private.pri:
../../../Qt/build/qtbase/mkspecs/modules/qt_lib_qmltest.pri:
../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_quick.pri:
../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_quick_private.pri:
../../../Qt/build/qtbase/mkspecs/modules/qt_lib_quick.pri:
../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_quickparticles_private.pri:
../../../Qt/build/qtbase/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_quickshapes_private.pri:
../../../Qt/build/qtbase/mkspecs/modules/qt_lib_quickshapes_private.pri:
../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_quickwidgets.pri:
../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_quickwidgets_private.pri:
../../../Qt/build/qtbase/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_service_support_private.pri:
../../../Qt/build/qtbase/mkspecs/modules/qt_lib_service_support_private.pri:
../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_svg.pri:
../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_svg_private.pri:
../../../Qt/build/qtbase/mkspecs/modules/qt_lib_svg.pri:
../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_testlib.pri:
../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_testlib_private.pri:
../../../Qt/build/qtbase/mkspecs/modules/qt_lib_testlib.pri:
../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_theme_support_private.pri:
../../../Qt/build/qtbase/mkspecs/modules/qt_lib_theme_support_private.pri:
../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_widgets.pri:
../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_widgets_private.pri:
../../../Qt/build/qtbase/mkspecs/modules/qt_lib_widgets.pri:
../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_xml.pri:
../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_xml_private.pri:
../../../Qt/build/qtbase/mkspecs/modules/qt_lib_xml.pri:
../../../Qt/build/qtbase/mkspecs/modules-inst/qt_lib_zlib_private.pri:
../../../Qt/build/qtbase/mkspecs/modules/qt_lib_zlib_private.pri:
../../../Qt/build/qtbase/mkspecs/modules/qt_plugin_qgif.pri:
../../../Qt/build/qtbase/mkspecs/modules/qt_plugin_qico.pri:
../../../Qt/build/qtbase/mkspecs/modules/qt_plugin_qjpeg.pri:
../../../Qt/build/qtbase/mkspecs/modules/qt_plugin_qsvg.pri:
../../../Qt/build/qtbase/mkspecs/modules/qt_plugin_qsvgicon.pri:
../../../Qt/build/qtbase/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri:
../../../Qt/build/qtbase/mkspecs/modules/qt_plugin_wasm.pri:
../../../Qt/build/qtbase/mkspecs/modules/qt_tool_syncqt.pri:
../../../Qt/5.12.0/Src/qtbase/mkspecs/features/qt_functions.prf:
../../../Qt/5.12.0/Src/qtbase/mkspecs/features/qt_config.prf:
../../../Qt/5.12.0/Src/qtbase/mkspecs/wasm-emscripten/qmake.conf:
../../../Qt/5.12.0/Src/qtbase/mkspecs/features/spec_post.prf:
.qmake.stash:
../../../Qt/5.12.0/Src/qtbase/mkspecs/features/exclusive_builds.prf:
../../../Qt/5.12.0/Src/qtbase/mkspecs/features/toolchain.prf:
../../../Qt/5.12.0/Src/qtbase/mkspecs/features/default_pre.prf:
../../../Qt/5.12.0/Src/qtbase/mkspecs/features/resolve_config.prf:
../../../Qt/5.12.0/Src/qtbase/mkspecs/features/default_post.prf:
../../../Qt/5.12.0/Src/qtbase/mkspecs/features/wasm/wasm.prf:
../../../Qt/5.12.0/Src/qtbase/mkspecs/features/warn_on.prf:
../../../Qt/build/qtbase/plugins/platforms/libwasm.prl:
../../../Qt/5.12.0/Src/qtbase/mkspecs/features/qt.prf:
../../../Qt/5.12.0/Src/qtbase/mkspecs/features/wasm/qt.prf:
../../../Qt/5.12.0/Src/qtbase/mkspecs/features/resources.prf:
../../../Qt/5.12.0/Src/qtbase/mkspecs/features/moc.prf:
../../../Qt/5.12.0/Src/qtbase/mkspecs/features/unix/opengl.prf:
../../../Qt/5.12.0/Src/qtbase/mkspecs/features/unix/thread.prf:
../../../Qt/5.12.0/Src/qtbase/mkspecs/features/qmake_use.prf:
../../../Qt/5.12.0/Src/qtbase/mkspecs/features/file_copies.prf:
../../../Qt/5.12.0/Src/qtbase/mkspecs/features/testcase_targets.prf:
../../../Qt/5.12.0/Src/qtbase/mkspecs/features/exceptions.prf:
../../../Qt/5.12.0/Src/qtbase/mkspecs/features/yacc.prf:
../../../Qt/5.12.0/Src/qtbase/mkspecs/features/lex.prf:
gui_opengl.pro:
../../../Qt/build/qtbase/lib/libQt5EventDispatcherSupport.prl:
../../../Qt/build/qtbase/lib/libQt5FontDatabaseSupport.prl:
../../../Qt/build/qtbase/lib/libqtfreetype.prl:
../../../Qt/build/qtbase/lib/libQt5EglSupport.prl:
../../../Qt/build/qtbase/lib/libQt5Gui.prl:
../../../Qt/build/qtbase/lib/libqtharfbuzz.prl:
../../../Qt/build/qtbase/lib/libQt5Core.prl:
../../../Qt/build/qtbase/lib/libqtpcre2.prl:
../../../Qt/build/qtbase/plugins/imageformats/libqgif.prl:
../../../Qt/build/qtbase/plugins/imageformats/libqico.prl:
../../../Qt/build/qtbase/plugins/imageformats/libqjpeg.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile gui_opengl.pro

qmake_all: FORCE


all: Makefile gui_opengl.js

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../../../Qt/5.12.0/Src/qtbase/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents hellowindow.h $(DISTDIR)/
	$(COPY_FILE) --parents hellowindow.cpp main.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) *.html *.js *.wasm /Users/ynumajir/Downloads/qt-webassembly-examples-master/gui_opengl/gui_opengl.js_plugin_import.cpp .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

apphtml: /Users/ynumajir/Qt/5.12.0/Src/qtbase/mkspecs/features/wasm/../../../src/plugins/platforms/wasm/wasm_shell.html
	sed -e s/APPNAME/gui_opengl/g /Users/ynumajir/Qt/5.12.0/Src/qtbase/mkspecs/features/wasm/../../../src/plugins/platforms/wasm/wasm_shell.html > /Users/ynumajir/Downloads/qt-webassembly-examples-master/gui_opengl/gui_opengl.html

appjs: /Users/ynumajir/Qt/5.12.0/Src/qtbase/mkspecs/features/wasm/../../../src/plugins/platforms/wasm/qtloader.js
	cp -f /Users/ynumajir/Qt/5.12.0/Src/qtbase/mkspecs/features/wasm/../../../src/plugins/platforms/wasm/qtloader.js /Users/ynumajir/Downloads/qt-webassembly-examples-master/gui_opengl

appsvg: /Users/ynumajir/Qt/5.12.0/Src/qtbase/mkspecs/features/wasm/../../../src/plugins/platforms/wasm/qtlogo.svg
	cp -f /Users/ynumajir/Qt/5.12.0/Src/qtbase/mkspecs/features/wasm/../../../src/plugins/platforms/wasm/qtlogo.svg /Users/ynumajir/Downloads/qt-webassembly-examples-master/gui_opengl

shellfiles: apphtml appjs appsvg

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_apphtml_make_all:
compiler_apphtml_clean:
	-$(DEL_FILE) gui_opengl.html
compiler_appjs_make_all:
compiler_appjs_clean:
	-$(DEL_FILE) qtloader.js
compiler_appsvg_make_all:
compiler_appsvg_clean:
	-$(DEL_FILE) qtlogo.svg
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: .moc/moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) .moc/moc_predefs.h
.moc/moc_predefs.h: ../../../Qt/5.12.0/Src/qtbase/mkspecs/features/data/dummy.cpp
	em++ -pipe -s USE_LIBPNG=1 -s USE_FREETYPE=1 -s USE_ZLIB=1 -O3 -std=gnu++11 -Wall -W -dM -E -o .moc/moc_predefs.h ../../../Qt/5.12.0/Src/qtbase/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean 

####### Compile

.obj/hellowindow.o: hellowindow.cpp hellowindow.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/QOpenGLWindow \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qopenglwindow.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/kernel/qopenglwindow.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qtguiglobal.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/kernel/qtguiglobal.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qglobal.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/global/qglobal.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qconfig-bootstrapped.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/global/qconfig-bootstrapped.h \
		../../../Qt/build/qtbase/include/QtCore/qconfig.h \
		../../../Qt/build/qtbase/src/corelib/global/qconfig.h \
		../../../Qt/build/qtbase/include/QtCore/qtcore-config.h \
		../../../Qt/build/qtbase/src/corelib/qtcore-config.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qsystemdetection.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/global/qsystemdetection.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qprocessordetection.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/global/qprocessordetection.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qcompilerdetection.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/global/qcompilerdetection.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qtypeinfo.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/global/qtypeinfo.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qsysinfo.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/global/qsysinfo.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qlogging.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/global/qlogging.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qflags.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/global/qflags.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qatomic.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/thread/qatomic.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qbasicatomic.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/thread/qbasicatomic.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qatomic_bootstrap.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/thread/qatomic_bootstrap.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qgenericatomic.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/thread/qgenericatomic.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qatomic_cxx11.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/thread/qatomic_cxx11.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qatomic_msvc.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/thread/qatomic_msvc.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qglobalstatic.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/global/qglobalstatic.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qmutex.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/thread/qmutex.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qnumeric.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/global/qnumeric.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qversiontagging.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/global/qversiontagging.h \
		../../../Qt/build/qtbase/include/QtGui/qtgui-config.h \
		../../../Qt/build/qtbase/src/gui/qtgui-config.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/QPaintDeviceWindow \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qpaintdevicewindow.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/kernel/qpaintdevicewindow.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/QWindow \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qwindow.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/kernel/qwindow.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/QObject \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qobject.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/kernel/qobject.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qobjectdefs.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/kernel/qobjectdefs.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qnamespace.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/global/qnamespace.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qobjectdefs_impl.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/kernel/qobjectdefs_impl.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qstring.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/tools/qstring.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qchar.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/tools/qchar.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qbytearray.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/tools/qbytearray.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qrefcount.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/tools/qrefcount.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qarraydata.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/tools/qarraydata.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qstringliteral.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/tools/qstringliteral.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qstringalgorithms.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/tools/qstringalgorithms.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qstringview.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/tools/qstringview.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qstringbuilder.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/tools/qstringbuilder.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qlist.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/tools/qlist.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qalgorithms.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/tools/qalgorithms.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qiterator.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/tools/qiterator.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qhashfunctions.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/tools/qhashfunctions.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qpair.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/tools/qpair.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qbytearraylist.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/tools/qbytearraylist.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qstringlist.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/tools/qstringlist.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qregexp.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/tools/qregexp.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qstringmatcher.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/tools/qstringmatcher.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qcoreevent.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/kernel/qcoreevent.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qscopedpointer.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/tools/qscopedpointer.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qmetatype.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/kernel/qmetatype.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qvarlengtharray.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/tools/qvarlengtharray.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qcontainerfwd.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/tools/qcontainerfwd.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qobject_impl.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/kernel/qobject_impl.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/QEvent \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/QMargins \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qmargins.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/tools/qmargins.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/QRect \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qrect.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/tools/qrect.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qsize.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/tools/qsize.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qpoint.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/tools/qpoint.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qsurface.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/kernel/qsurface.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qsurfaceformat.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/kernel/qsurfaceformat.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qwindowdefs.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/kernel/qwindowdefs.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qwindowdefs_win.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/kernel/qwindowdefs_win.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qicon.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/image/qicon.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qpixmap.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/image/qpixmap.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qpaintdevice.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/painting/qpaintdevice.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qcolor.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/painting/qcolor.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qrgb.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/painting/qrgb.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qrgba64.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/painting/qrgba64.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qsharedpointer.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/tools/qsharedpointer.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qshareddata.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/tools/qshareddata.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qhash.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/tools/qhash.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qsharedpointer_impl.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/tools/qsharedpointer_impl.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qimage.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/image/qimage.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qpixelformat.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/kernel/qpixelformat.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qtransform.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/painting/qtransform.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qmatrix.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/painting/qmatrix.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qpolygon.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/painting/qpolygon.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qvector.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/tools/qvector.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qregion.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/painting/qregion.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qdatastream.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/serialization/qdatastream.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qiodevice.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/io/qiodevice.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qline.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/tools/qline.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qpainterpath.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/painting/qpainterpath.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qcursor.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/kernel/qcursor.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/QPaintDevice \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/QOpenGLContext \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qopenglcontext.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/kernel/qopenglcontext.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/QScopedPointer \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/QSurfaceFormat \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qopengl.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/opengl/qopengl.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qt_windows.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/global/qt_windows.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qopengles2ext.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/opengl/qopengles2ext.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qopenglext.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/opengl/qopenglext.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qopenglversionfunctions.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/opengl/qopenglversionfunctions.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qvariant.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/kernel/qvariant.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qmap.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/tools/qmap.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qdebug.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/io/qdebug.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qtextstream.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/serialization/qtextstream.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qlocale.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/tools/qlocale.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qset.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/tools/qset.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qcontiguouscache.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/tools/qcontiguouscache.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/QImage \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/QColor \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/QOpenGLShaderProgram \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qopenglshaderprogram.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/opengl/qopenglshaderprogram.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qvector2d.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/math3d/qvector2d.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qvector3d.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/math3d/qvector3d.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qvector4d.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/math3d/qvector4d.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qmatrix4x4.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/math3d/qmatrix4x4.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qquaternion.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/math3d/qquaternion.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qgenericmatrix.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/math3d/qgenericmatrix.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/QExposeEvent \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qevent.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/kernel/qevent.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qkeysequence.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/kernel/qkeysequence.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qurl.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/io/qurl.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qurlquery.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/io/qurlquery.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qfile.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/io/qfile.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qfiledevice.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/io/qfiledevice.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qtouchdevice.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/kernel/qtouchdevice.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qmath.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/kernel/qmath.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/hellowindow.o hellowindow.cpp

.obj/main.o: main.cpp hellowindow.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/QOpenGLWindow \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qopenglwindow.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/kernel/qopenglwindow.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qtguiglobal.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/kernel/qtguiglobal.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qglobal.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/global/qglobal.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qconfig-bootstrapped.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/global/qconfig-bootstrapped.h \
		../../../Qt/build/qtbase/include/QtCore/qconfig.h \
		../../../Qt/build/qtbase/src/corelib/global/qconfig.h \
		../../../Qt/build/qtbase/include/QtCore/qtcore-config.h \
		../../../Qt/build/qtbase/src/corelib/qtcore-config.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qsystemdetection.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/global/qsystemdetection.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qprocessordetection.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/global/qprocessordetection.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qcompilerdetection.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/global/qcompilerdetection.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qtypeinfo.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/global/qtypeinfo.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qsysinfo.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/global/qsysinfo.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qlogging.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/global/qlogging.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qflags.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/global/qflags.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qatomic.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/thread/qatomic.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qbasicatomic.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/thread/qbasicatomic.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qatomic_bootstrap.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/thread/qatomic_bootstrap.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qgenericatomic.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/thread/qgenericatomic.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qatomic_cxx11.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/thread/qatomic_cxx11.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qatomic_msvc.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/thread/qatomic_msvc.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qglobalstatic.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/global/qglobalstatic.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qmutex.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/thread/qmutex.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qnumeric.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/global/qnumeric.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qversiontagging.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/global/qversiontagging.h \
		../../../Qt/build/qtbase/include/QtGui/qtgui-config.h \
		../../../Qt/build/qtbase/src/gui/qtgui-config.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/QPaintDeviceWindow \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qpaintdevicewindow.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/kernel/qpaintdevicewindow.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/QWindow \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qwindow.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/kernel/qwindow.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/QObject \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qobject.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/kernel/qobject.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qobjectdefs.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/kernel/qobjectdefs.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qnamespace.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/global/qnamespace.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qobjectdefs_impl.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/kernel/qobjectdefs_impl.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qstring.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/tools/qstring.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qchar.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/tools/qchar.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qbytearray.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/tools/qbytearray.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qrefcount.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/tools/qrefcount.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qarraydata.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/tools/qarraydata.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qstringliteral.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/tools/qstringliteral.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qstringalgorithms.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/tools/qstringalgorithms.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qstringview.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/tools/qstringview.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qstringbuilder.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/tools/qstringbuilder.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qlist.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/tools/qlist.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qalgorithms.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/tools/qalgorithms.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qiterator.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/tools/qiterator.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qhashfunctions.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/tools/qhashfunctions.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qpair.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/tools/qpair.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qbytearraylist.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/tools/qbytearraylist.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qstringlist.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/tools/qstringlist.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qregexp.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/tools/qregexp.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qstringmatcher.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/tools/qstringmatcher.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qcoreevent.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/kernel/qcoreevent.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qscopedpointer.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/tools/qscopedpointer.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qmetatype.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/kernel/qmetatype.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qvarlengtharray.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/tools/qvarlengtharray.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qcontainerfwd.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/tools/qcontainerfwd.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qobject_impl.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/kernel/qobject_impl.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/QEvent \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/QMargins \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qmargins.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/tools/qmargins.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/QRect \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qrect.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/tools/qrect.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qsize.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/tools/qsize.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qpoint.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/tools/qpoint.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qsurface.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/kernel/qsurface.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qsurfaceformat.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/kernel/qsurfaceformat.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qwindowdefs.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/kernel/qwindowdefs.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qwindowdefs_win.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/kernel/qwindowdefs_win.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qicon.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/image/qicon.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qpixmap.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/image/qpixmap.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qpaintdevice.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/painting/qpaintdevice.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qcolor.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/painting/qcolor.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qrgb.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/painting/qrgb.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qrgba64.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/painting/qrgba64.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qsharedpointer.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/tools/qsharedpointer.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qshareddata.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/tools/qshareddata.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qhash.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/tools/qhash.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qsharedpointer_impl.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/tools/qsharedpointer_impl.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qimage.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/image/qimage.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qpixelformat.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/kernel/qpixelformat.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qtransform.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/painting/qtransform.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qmatrix.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/painting/qmatrix.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qpolygon.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/painting/qpolygon.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qvector.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/tools/qvector.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qregion.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/painting/qregion.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qdatastream.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/serialization/qdatastream.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qiodevice.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/io/qiodevice.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qline.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/tools/qline.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qpainterpath.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/painting/qpainterpath.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qcursor.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/kernel/qcursor.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/QPaintDevice \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/QOpenGLContext \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qopenglcontext.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/kernel/qopenglcontext.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/QScopedPointer \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/QSurfaceFormat \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qopengl.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/opengl/qopengl.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qt_windows.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/global/qt_windows.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qopengles2ext.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/opengl/qopengles2ext.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qopenglext.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/opengl/qopenglext.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qopenglversionfunctions.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/opengl/qopenglversionfunctions.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qvariant.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/kernel/qvariant.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qmap.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/tools/qmap.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qdebug.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/io/qdebug.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qtextstream.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/serialization/qtextstream.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qlocale.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/tools/qlocale.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qset.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/tools/qset.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qcontiguouscache.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/tools/qcontiguouscache.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/QImage \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/QColor \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/QOpenGLShaderProgram \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qopenglshaderprogram.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/opengl/qopenglshaderprogram.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qvector2d.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/math3d/qvector2d.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qvector3d.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/math3d/qvector3d.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qvector4d.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/math3d/qvector4d.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qmatrix4x4.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/math3d/qmatrix4x4.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qquaternion.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/math3d/qquaternion.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qgenericmatrix.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/math3d/qgenericmatrix.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/QtGui \
		../../../Qt/build/qtbase/include/QtGui/QtGuiDepends \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/QtCore \
		../../../Qt/build/qtbase/include/QtCore/QtCoreDepends \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qabstractanimation.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/animation/qabstractanimation.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qabstracteventdispatcher.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/kernel/qabstracteventdispatcher.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qeventloop.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/kernel/qeventloop.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qabstractitemmodel.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/itemmodels/qabstractitemmodel.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qabstractnativeeventfilter.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/kernel/qabstractnativeeventfilter.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qabstractproxymodel.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/itemmodels/qabstractproxymodel.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qabstractstate.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/statemachine/qabstractstate.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qabstracttransition.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/statemachine/qabstracttransition.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qanimationgroup.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/animation/qanimationgroup.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qarraydataops.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/tools/qarraydataops.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qarraydatapointer.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/tools/qarraydatapointer.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qbasictimer.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/kernel/qbasictimer.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qbitarray.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/tools/qbitarray.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qbuffer.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/io/qbuffer.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qbytearraymatcher.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/tools/qbytearraymatcher.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qcache.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/tools/qcache.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qcborarray.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/serialization/qcborarray.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qcborvalue.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/serialization/qcborvalue.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qdatetime.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/tools/qdatetime.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qcborcommon.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/serialization/qcborcommon.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qregularexpression.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/tools/qregularexpression.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qurl.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/io/qurl.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qurlquery.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/io/qurlquery.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/quuid.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/plugin/quuid.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qcbormap.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/serialization/qcbormap.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qcborstream.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/serialization/qcborstream.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qfloat16.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/global/qfloat16.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qcollator.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/tools/qcollator.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qcommandlineoption.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/tools/qcommandlineoption.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qcommandlineparser.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/tools/qcommandlineparser.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qcoreapplication.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/kernel/qcoreapplication.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qcryptographichash.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/tools/qcryptographichash.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qdeadlinetimer.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/kernel/qdeadlinetimer.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qelapsedtimer.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/kernel/qelapsedtimer.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qdir.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/io/qdir.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qfileinfo.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/io/qfileinfo.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qfile.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/io/qfile.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qfiledevice.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/io/qfiledevice.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qdiriterator.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/io/qdiriterator.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qeasingcurve.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/tools/qeasingcurve.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qendian.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/global/qendian.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qeventtransition.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/statemachine/qeventtransition.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qexception.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/thread/qexception.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qfactoryinterface.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/plugin/qfactoryinterface.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qfileselector.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/io/qfileselector.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/QStringList \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qfilesystemwatcher.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/io/qfilesystemwatcher.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qfinalstate.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/statemachine/qfinalstate.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qfuture.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/thread/qfuture.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qfutureinterface.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/thread/qfutureinterface.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qrunnable.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/thread/qrunnable.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qresultstore.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/thread/qresultstore.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qfuturesynchronizer.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/thread/qfuturesynchronizer.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qfuturewatcher.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/thread/qfuturewatcher.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qhistorystate.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/statemachine/qhistorystate.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qidentityproxymodel.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/itemmodels/qidentityproxymodel.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qisenum.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/global/qisenum.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qitemselectionmodel.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/itemmodels/qitemselectionmodel.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qjsonarray.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/serialization/qjsonarray.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qjsonvalue.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/serialization/qjsonvalue.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qjsondocument.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/serialization/qjsondocument.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qjsonobject.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/serialization/qjsonobject.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qlibrary.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/plugin/qlibrary.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qlibraryinfo.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/global/qlibraryinfo.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qversionnumber.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/tools/qversionnumber.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qlinkedlist.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/tools/qlinkedlist.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qlockfile.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/io/qlockfile.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qloggingcategory.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/io/qloggingcategory.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qmath.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/kernel/qmath.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qmessageauthenticationcode.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/tools/qmessageauthenticationcode.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qmetaobject.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/kernel/qmetaobject.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qmimedata.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/kernel/qmimedata.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qmimedatabase.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/mimetypes/qmimedatabase.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qmimetype.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/mimetypes/qmimetype.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qobjectcleanuphandler.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/kernel/qobjectcleanuphandler.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qoperatingsystemversion.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/global/qoperatingsystemversion.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qparallelanimationgroup.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/animation/qparallelanimationgroup.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qpauseanimation.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/animation/qpauseanimation.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qplugin.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/plugin/qplugin.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qpointer.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/kernel/qpointer.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qpluginloader.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/plugin/qpluginloader.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qprocess.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/io/qprocess.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qpropertyanimation.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/animation/qpropertyanimation.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qvariantanimation.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/animation/qvariantanimation.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qqueue.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/tools/qqueue.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qrandom.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/global/qrandom.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qreadwritelock.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/thread/qreadwritelock.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qresource.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/io/qresource.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qsavefile.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/io/qsavefile.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qscopedvaluerollback.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/tools/qscopedvaluerollback.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qscopeguard.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/tools/qscopeguard.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qsemaphore.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/thread/qsemaphore.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qsequentialanimationgroup.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/animation/qsequentialanimationgroup.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qsettings.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/io/qsettings.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qsharedmemory.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/kernel/qsharedmemory.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qsignalmapper.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/kernel/qsignalmapper.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qsignaltransition.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/statemachine/qsignaltransition.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qsocketnotifier.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/kernel/qsocketnotifier.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qsortfilterproxymodel.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/itemmodels/qsortfilterproxymodel.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qstack.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/tools/qstack.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qstandardpaths.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/io/qstandardpaths.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qstate.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/statemachine/qstate.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qstatemachine.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/statemachine/qstatemachine.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qstorageinfo.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/io/qstorageinfo.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qstringlistmodel.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/itemmodels/qstringlistmodel.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qsystemsemaphore.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/kernel/qsystemsemaphore.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qtemporarydir.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/io/qtemporarydir.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qtemporaryfile.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/io/qtemporaryfile.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qtextboundaryfinder.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/tools/qtextboundaryfinder.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qtextcodec.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/codecs/qtextcodec.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qthread.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/thread/qthread.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qthreadpool.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/thread/qthreadpool.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qthreadstorage.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/thread/qthreadstorage.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qtimeline.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/tools/qtimeline.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qtimer.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/kernel/qtimer.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qtimezone.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/tools/qtimezone.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qtranslator.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/kernel/qtranslator.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qtypetraits.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/global/qtypetraits.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qwaitcondition.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/thread/qwaitcondition.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qwineventnotifier.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/kernel/qwineventnotifier.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qxmlstream.h \
		../../../Qt/5.12.0/Src/qtbase/src/corelib/serialization/qxmlstream.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/qtcoreversion.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qabstracttextdocumentlayout.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/text/qabstracttextdocumentlayout.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qtextlayout.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/text/qtextlayout.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qevent.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/kernel/qevent.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qkeysequence.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/kernel/qkeysequence.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qtouchdevice.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/kernel/qtouchdevice.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qtextformat.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/text/qtextformat.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qfont.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/text/qfont.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qpen.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/painting/qpen.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qbrush.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/painting/qbrush.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qtextoption.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/text/qtextoption.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qglyphrun.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/text/qglyphrun.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qrawfont.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/text/qrawfont.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qfontdatabase.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/text/qfontdatabase.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qtextcursor.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/text/qtextcursor.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qtextdocument.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/text/qtextdocument.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qpalette.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/kernel/qpalette.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qaccessible.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/accessible/qaccessible.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qaccessiblebridge.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/accessible/qaccessiblebridge.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qaccessibleobject.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/accessible/qaccessibleobject.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qaccessibleplugin.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/accessible/qaccessibleplugin.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qbackingstore.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/painting/qbackingstore.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qbitmap.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/image/qbitmap.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qclipboard.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/kernel/qclipboard.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qdesktopservices.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/util/qdesktopservices.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qdrag.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/kernel/qdrag.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qfontinfo.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/text/qfontinfo.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qfontmetrics.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/text/qfontmetrics.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qgenericplugin.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/kernel/qgenericplugin.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qgenericpluginfactory.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/kernel/qgenericpluginfactory.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qguiapplication.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/kernel/qguiapplication.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qinputmethod.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/kernel/qinputmethod.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qiconengine.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/image/qiconengine.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qiconengineplugin.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/image/qiconengineplugin.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qimageiohandler.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/image/qimageiohandler.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qimagereader.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/image/qimagereader.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qimagewriter.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/image/qimagewriter.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qmovie.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/image/qmovie.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qoffscreensurface.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/kernel/qoffscreensurface.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qopenglbuffer.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/opengl/qopenglbuffer.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qopengldebug.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/opengl/qopengldebug.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qopenglextrafunctions.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/opengl/qopenglextrafunctions.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qopenglfunctions.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/opengl/qopenglfunctions.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qopenglframebufferobject.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/opengl/qopenglframebufferobject.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qopenglpaintdevice.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/opengl/qopenglpaintdevice.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qopenglpixeltransferoptions.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/opengl/qopenglpixeltransferoptions.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/QSharedDataPointer \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qopengltexture.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/opengl/qopengltexture.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qopengltextureblitter.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/opengl/qopengltextureblitter.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/QMatrix3x3 \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/QMatrix4x4 \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qopengltimerquery.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/opengl/qopengltimerquery.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qopenglvertexarrayobject.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/opengl/qopenglvertexarrayobject.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qpagedpaintdevice.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/painting/qpagedpaintdevice.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qpagelayout.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/painting/qpagelayout.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qpagesize.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/painting/qpagesize.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qpaintengine.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/painting/qpaintengine.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qpainter.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/painting/qpainter.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qpdfwriter.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/painting/qpdfwriter.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qpicture.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/image/qpicture.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qpictureformatplugin.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/image/qpictureformatplugin.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qpixmapcache.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/image/qpixmapcache.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qrasterwindow.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/kernel/qrasterwindow.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qscreen.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/kernel/qscreen.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/QList \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/QSize \
		../../../Qt/5.12.0/Src/qtbase/include/QtCore/QSizeF \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/QTransform \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qsessionmanager.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/kernel/qsessionmanager.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qstandarditemmodel.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/itemmodels/qstandarditemmodel.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qstatictext.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/text/qstatictext.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qstylehints.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/kernel/qstylehints.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qsyntaxhighlighter.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/text/qsyntaxhighlighter.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qtextobject.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/text/qtextobject.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qtextdocumentfragment.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/text/qtextdocumentfragment.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qtextdocumentwriter.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/text/qtextdocumentwriter.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qtextlist.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/text/qtextlist.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qtexttable.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/text/qtexttable.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qvalidator.h \
		../../../Qt/5.12.0/Src/qtbase/src/gui/util/qvalidator.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/qtguiversion.h \
		../../../Qt/5.12.0/Src/qtbase/include/QtGui/QScreen
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/main.o main.cpp

.obj/gui_opengl.js_plugin_import.o: /Users/ynumajir/Downloads/qt-webassembly-examples-master/gui_opengl/gui_opengl.js_plugin_import.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/gui_opengl.js_plugin_import.o /Users/ynumajir/Downloads/qt-webassembly-examples-master/gui_opengl/gui_opengl.js_plugin_import.cpp

####### Install

install_js_file: first FORCE
	@test -d $(INSTALL_ROOT)/Users/ynumajir/Downloads/qt-webassembly-examples-master/gui_opengl/./ || mkdir -p $(INSTALL_ROOT)/Users/ynumajir/Downloads/qt-webassembly-examples-master/gui_opengl/./
	-$(QINSTALL_PROGRAM) /Users/ynumajir/Downloads/qt-webassembly-examples-master/gui_opengl/gui_opengl.js $(INSTALL_ROOT)/Users/ynumajir/Downloads/qt-webassembly-examples-master/gui_opengl/./gui_opengl.js

uninstall_js_file: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/Users/ynumajir/Downloads/qt-webassembly-examples-master/gui_opengl/./gui_opengl.js
	-$(DEL_DIR) $(INSTALL_ROOT)/Users/ynumajir/Downloads/qt-webassembly-examples-master/gui_opengl/./ 


install: install_js_file  FORCE

uninstall: uninstall_js_file  FORCE

FORCE:

